

# This file was *autogenerated* from the file ellipticTorsion.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
x = var('x')
__tmp__=var("x"); f = symbolic_expression(x**_sage_const_3  - _sage_const_4 *x + _sage_const_4 ).function(x)
x_infty = f(x).roots(x, ring=RR, multiplicities=False)[_sage_const_0 ]
Omega = integrate(_sage_const_1 /sqrt(f(x)), x, x_infty, infinity)
x_0 = _sage_const_2  
print(N(integrate(_sage_const_1 /sqrt(f(x)), x, x_0, infinity)/(_sage_const_2 *Omega)))


